apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-runner
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job-runner
            image: local/job-runner:2.0
            imagePullPolicy: Never
            env: 
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: moc-s3-credentials
                  key: accesskey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: moc-s3-credentials
                  key: secretkey
            args:
            - /batchjob/main.py
            - /batchjob/moc
            - <gateway_url>
            - <tag>
            - <S3_domain_name>
            - <S3_path>
            - <input_filename_prefix>
            - <output_filename_prefix>
            - <any_other_flags>
          restartPolicy: OnFailure
